[package]
name = "ratsnest"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
crossterm = "0.29.0"
fuzzy-matcher = "0.3.7"
ignore = "0.4.23"
ratatui = "0.29.0"
tokio = { version = "1.47.1", features = ["full"] }
